version: '3.7'

services:
  postgres:
    build: ./postgres
    restart: always
    env_file:
      - .env
    image: iamdavidmiguelalvarez/asv:postgres
    volumes:
    - data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  data: