# Generated by Django 4.0.3 on 2023-04-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='air_bags_deployed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='miles',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='offer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='runs_and_drives',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='sale_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='saleprice',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='starts_at_checkin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
