# Generated by Django 4.0.3 on 2023-04-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asv', '0002_alter_truck_air_bags_deployed_alter_truck_miles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='air_bags_deployed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='branch_zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='cabtype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='damage_description_primary',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='data_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='drivelinetype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='enginesize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fueltype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='loss_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='miles',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='offer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='runs_and_drives',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='saledocumenttype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='saleprice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='starts_at_checkin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='stateabbreviation',
            field=models.CharField(max_length=5),
        ),
    ]
