# Generated by Django 4.0.3 on 2023-04-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asv', '0003_alter_truck_air_bags_deployed_alter_truck_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(max_length=255),
        ),
    ]
