# Generated by Django 4.0.3 on 2023-05-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asv', '0005_branch_make_model_trim_vehiclecondition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='make',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='trim',
            name='trim',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
