# Generated by Django 4.2.1 on 2023-07-30 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asv', '0008_remove_model_make_model_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_date_new',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 5, 54, 28, 221370)),
        ),
    ]
